# Navigation menus

[[main]]
  name = "posts"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "photography"
  pageRef = "posts/photography"
  weight = 20

[[main]]
  name = "visual"
  pageRef = "visual-thinking"
  weight = 25

[[main]]
  name = "tags"
  pageRef = "tags"
  weight = 30

[[main]]
  name = "about"
  pageRef = "about"
  weight = 40

[[main]]
  identifier = "search"
  name = "Search"
  weight = 99
  [main.params]
    action = "search"
    icon = "search"
